### ISSUE TITLE
Show password instructions when making an account

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-mlhframework#60]
Likely an upstream fix, but could be something we can customize through docassemble, either by changing the rules, or by changing the login screen

Google doc comment link: ?disco=AAABDEjMkwQ

**Comment by BryceStevenWilley** [comment]
Looks like we can mostly do it through config values. Not perfect, but easier than getting an upstream fix in.

https://docassemble.org/docs/config.html#customization

Added some of our terms to translate in `us-words.yml` (PR to come)

Will add the following bit to the config:

```yaml
register page heading: Sign up
register page title: Sign up
register page tab title: Sign up
register page submit: |
  Your password must be 6 characters long with 1 lowercase, 1 uppercase, and 1 number.
```

The latter password complexity is something that we can change as well; for now we'll just have to remember to change this message if we change the complexity requirements as well.
